/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/LetterCell copy.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LetterCell: typeof import('./src/components/LetterCell.vue')['default']
    LetterGrid: typeof import('./src/components/LetterGrid.vue')['default']
  }
}
